services:
  # Base de données PostgreSQL pour l'API
  db:
    image: pgvector/pgvector:pg16
    container_name: postgres_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Base de données MySQL pour GLPI
  mysql:
    image: mysql:8.0
    container_name: glpi_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=glpidb
      - MYSQL_USER=glpi
      - MYSQL_PASSWORD=glpi
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # GLPI
  glpi:
    image: diouxx/glpi:latest
    platform: linux/amd64
    container_name: glpi_app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8083:80"
    environment:
      - TIMEZONE=Europe/Paris
    volumes:
      - glpi_data:/var/www/html/glpi
    restart: unless-stopped

  # API FastAPI
  api:
    build: ./backend
    container_name: fastapi_api
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started
      glpi:
        condition: service_started
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/mydatabase
      - OLLAMA_HOST=http://ollama:11434
      # GLPI dans Docker
      - GLPI_URL=http://glpi:80/apirest.php
      - GLPI_USER=glpi
      - GLPI_PASSWORD=glpi
      - GLPI_APP_TOKEN=GbHoo7eDoFfTq6lchS2ESmGbmsY2IHkKrnB7WST2
      - USE_MOCK=false
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./backend/app:/app/app
      - ./frontend:/app/frontend
    restart: unless-stopped
    
  # Ollama
  ollama:
    image: ollama/ollama
    container_name: ollama_service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  postgres_data:
  mysql_data:
  glpi_data:
  ollama_data: